# Generated by Django 5.1.7 on 2025-10-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='subtotal',
            new_name='price',
        ),
    ]
